/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.poo.interfaces;

import br.com.poo.modelo.Carrinho;
import br.com.poo.modelo.Data;
import br.com.poo.modelo.Evento;
import br.com.poo.modelo.Hora;
import br.com.poo.modelo.Local;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.DefaultRowSorter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nirton Afonso
 * @author Ilmar Macedo
 */
public class BalcaoIngresso extends javax.swing.JFrame {

    /**
     * Creates new form BalcaoIngresso
     */
    public String nome;
    // public String nomeCarrinho;
    // public double valorCarrinho;
    public int quantComprado;
    public int dia;
    public int mes;
    public int ano;
    public int hora;
    public int minuto;
    public String artista;
    public String local;
    public int capacidadePessoas;
    public double valor;

    public int posicao = 0;
    public int posicao2 = 0;
    public double totalCompra = 0;
    public int selecionado = 0;
    public int selecionadoCarrinho = 0;
    public Evento evento;
    private static BalcaoIngresso bi;
    public List<Evento> listaEventos = new ArrayList<>();
    public List<Carrinho> listaCarrinho = new ArrayList<>();
    DefaultListModel lista = new DefaultListModel();
    InterfaceIngresso ingresso = new InterfaceIngresso();

    public BalcaoIngresso() {

        initComponents();
        menu();
        perfumaria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Camadas = new javax.swing.JLayeredPane();
        jMenu = new javax.swing.JPanel();
        btnFinalizarCompra = new javax.swing.JButton();
        btnComprarIngresso = new javax.swing.JButton();
        btnVoltar4 = new javax.swing.JButton();
        ImgMenu = new javax.swing.JLabel();
        jGuiche = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEventos = new javax.swing.JList<>();
        txtQuantidade = new javax.swing.JTextField();
        lblEventos = new javax.swing.JLabel();
        lblQuatidade = new javax.swing.JLabel();
        lblGuiche = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfoEvento = new javax.swing.JTextArea();
        lblInfoEvento = new javax.swing.JLabel();
        jAdicionar = new javax.swing.JPanel();
        lblNomeEvento = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblLocalEvento = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblCapacidadeMaxima = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeEvento = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        txtLocalEvento = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtMinuto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtCapMaxima = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnVoltar2 = new javax.swing.JButton();
        jCarrinhoDeCompras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblTotalConta = new javax.swing.JLabel();
        btnVoltar6 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jMainMenu = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ImgMenu2 = new javax.swing.JLabel();
        jPromotorMenu = new javax.swing.JPanel();
        btnAddIngressos = new javax.swing.JButton();
        bntRemoverIngresso = new javax.swing.JButton();
        btnEditarIngresso = new javax.swing.JButton();
        btnVoltar5 = new javax.swing.JButton();
        ImgMenu1 = new javax.swing.JLabel();
        jRemoverEvento = new javax.swing.JPanel();
        btnDeletar = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstEventos1 = new javax.swing.JList<>();
        lblEventos1 = new javax.swing.JLabel();
        lblGuiche1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtInfoEvento1 = new javax.swing.JTextArea();
        lblInfoEvento1 = new javax.swing.JLabel();
        jGuicheAlterar = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnVoltar3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstAlterarEventos = new javax.swing.JList<>();
        lblEventos2 = new javax.swing.JLabel();
        lblGuiche2 = new javax.swing.JLabel();
        lblAlterarArtista = new javax.swing.JLabel();
        lblAlterarData = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAlterarDia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAlterarAno = new javax.swing.JTextField();
        txtAlterarArtista = new javax.swing.JTextField();
        txtAlterarValor = new javax.swing.JTextField();
        txtAlterarCapMaxima = new javax.swing.JTextField();
        lblAlterarCapacidadeMaxima = new javax.swing.JLabel();
        lblAlterarLocalEvento = new javax.swing.JLabel();
        lblAlterarValor = new javax.swing.JLabel();
        txtAlterarMes = new javax.swing.JTextField();
        lblAlterarHorario = new javax.swing.JLabel();
        txtAlterarLocalEvento = new javax.swing.JTextField();
        txtAlterarMinuto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAlterarNomeEvento = new javax.swing.JTextField();
        txtAlterarHora = new javax.swing.JTextField();
        lblAlterarNomeEvento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setName("Balcao"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Camadas.setLayout(new java.awt.GridBagLayout());

        jMenu.setMaximumSize(new java.awt.Dimension(600, 500));
        jMenu.setMinimumSize(new java.awt.Dimension(600, 500));
        jMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFinalizarCompra.setText("CARRINHO DE COMPRAS");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });
        jMenu.add(btnFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 190, 40));

        btnComprarIngresso.setText("COMPRAR INGRESSOS");
        btnComprarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarIngressoActionPerformed(evt);
            }
        });
        jMenu.add(btnComprarIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 40));

        btnVoltar4.setText("VOLTAR");
        btnVoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar4ActionPerformed(evt);
            }
        });
        jMenu.add(btnVoltar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        ImgMenu.setMaximumSize(new java.awt.Dimension(520, 460));
        ImgMenu.setMinimumSize(new java.awt.Dimension(520, 460));
        jMenu.add(ImgMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Camadas.add(jMenu, gridBagConstraints);

        jGuiche.setAlignmentX(0.0F);
        jGuiche.setAlignmentY(0.0F);
        jGuiche.setMaximumSize(new java.awt.Dimension(600, 500));
        jGuiche.setMinimumSize(new java.awt.Dimension(600, 500));
        jGuiche.setPreferredSize(new java.awt.Dimension(620, 522));

        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lstEventos.setModel(lista);
        lstEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEventos);

        lblEventos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventos.setText("EVENTOS");

        lblQuatidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuatidade.setText("Quantidade:");

        lblGuiche.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGuiche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuiche.setText("GUICHE");

        txtInfoEvento.setEditable(false);
        txtInfoEvento.setColumns(20);
        txtInfoEvento.setRows(5);
        jScrollPane2.setViewportView(txtInfoEvento);

        lblInfoEvento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfoEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoEvento.setText("Informações do Evento");

        javax.swing.GroupLayout jGuicheLayout = new javax.swing.GroupLayout(jGuiche);
        jGuiche.setLayout(jGuicheLayout);
        jGuicheLayout.setHorizontalGroup(
            jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuicheLayout.createSequentialGroup()
                .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jGuicheLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jGuicheLayout.createSequentialGroup()
                        .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jGuicheLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jGuicheLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jGuicheLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblInfoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jGuicheLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltar)
                                .addGap(141, 141, 141)
                                .addComponent(lblGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jGuicheLayout.createSequentialGroup()
                                .addComponent(lblQuatidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jGuicheLayout.setVerticalGroup(
            jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuicheLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addComponent(lblGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jGuicheLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuatidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jGuicheLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblInfoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jGuiche, gridBagConstraints);

        jAdicionar.setAlignmentX(0.0F);
        jAdicionar.setAlignmentY(0.0F);
        jAdicionar.setMaximumSize(new java.awt.Dimension(600, 500));
        jAdicionar.setMinimumSize(new java.awt.Dimension(600, 500));
        jAdicionar.setPreferredSize(new java.awt.Dimension(620, 522));

        lblNomeEvento.setText("Nome do Evento");

        lblArtista.setText("Artista");

        lblLocalEvento.setText("Local do Evento");

        lblData.setText("Data (DD/MM/AAAA)");

        lblHorario.setText("Horário");

        lblValor.setText("Valor R$");

        lblCapacidadeMaxima.setText("Capacidade Máxima");

        jLabel8.setText("/");

        jLabel9.setText("/");
        jLabel9.setToolTipText("");

        jLabel10.setText(":");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnVoltar2.setText("VOLTAR");
        btnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAdicionarLayout = new javax.swing.GroupLayout(jAdicionar);
        jAdicionar.setLayout(jAdicionarLayout);
        jAdicionarLayout.setHorizontalGroup(
            jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdicionarLayout.createSequentialGroup()
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAdicionarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jAdicionarLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jAdicionarLayout.createSequentialGroup()
                                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLocalEvento)
                                    .addComponent(lblArtista)
                                    .addComponent(lblNomeEvento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeEvento)
                                    .addComponent(txtArtista)
                                    .addComponent(txtLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jAdicionarLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHorario)
                                    .addComponent(lblData)
                                    .addComponent(lblValor)
                                    .addComponent(lblCapacidadeMaxima))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jAdicionarLayout.createSequentialGroup()
                                        .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHora)
                                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMes)
                                            .addComponent(txtMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtValor)
                                    .addComponent(txtCapMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jAdicionarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jAdicionarLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jAdicionarLayout.setVerticalGroup(
            jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar2)
                .addGap(70, 70, 70)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEvento)
                    .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArtista)
                    .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalEvento)
                    .addComponent(txtLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidadeMaxima)
                    .addComponent(txtCapMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jAdicionar, gridBagConstraints);

        jCarrinhoDeCompras.setAlignmentX(0.0F);
        jCarrinhoDeCompras.setAlignmentY(0.0F);
        jCarrinhoDeCompras.setMaximumSize(new java.awt.Dimension(600, 500));
        jCarrinhoDeCompras.setMinimumSize(new java.awt.Dimension(600, 500));
        jCarrinhoDeCompras.setPreferredSize(new java.awt.Dimension(620, 522));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meu Carrinho");

        jTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Evento", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTableList.getTableHeader().setReorderingAllowed(false);
        jTableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableList);
        if (jTableList.getColumnModel().getColumnCount() > 0) {
            jTableList.getColumnModel().getColumn(0).setResizable(false);
            jTableList.getColumnModel().getColumn(1).setResizable(false);
            jTableList.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL DA COMPRA");

        lblTotalConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalConta.setForeground(new java.awt.Color(255, 0, 0));

        btnVoltar6.setText("VOLTAR");
        btnVoltar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar6ActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir Ingresso");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCarrinhoDeComprasLayout = new javax.swing.GroupLayout(jCarrinhoDeCompras);
        jCarrinhoDeCompras.setLayout(jCarrinhoDeComprasLayout);
        jCarrinhoDeComprasLayout.setHorizontalGroup(
            jCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCarrinhoDeComprasLayout.createSequentialGroup()
                .addGroup(jCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCarrinhoDeComprasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnVoltar6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCarrinhoDeComprasLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCarrinhoDeComprasLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalConta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jCarrinhoDeComprasLayout.setVerticalGroup(
            jCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCarrinhoDeComprasLayout.createSequentialGroup()
                .addGroup(jCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jCarrinhoDeComprasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jCarrinhoDeComprasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalConta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jCarrinhoDeCompras, gridBagConstraints);

        jMainMenu.setAlignmentX(0.0F);
        jMainMenu.setAlignmentY(0.0F);
        jMainMenu.setMaximumSize(new java.awt.Dimension(600, 500));
        jMainMenu.setMinimumSize(new java.awt.Dimension(600, 500));
        jMainMenu.setPreferredSize(new java.awt.Dimension(620, 522));
        jMainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("PROMOTOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jMainMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, 170));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("CLIENTE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jMainMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 210, 170));

        ImgMenu2.setMaximumSize(new java.awt.Dimension(520, 460));
        ImgMenu2.setMinimumSize(new java.awt.Dimension(520, 460));
        ImgMenu2.setPreferredSize(new java.awt.Dimension(600, 500));
        jMainMenu.add(ImgMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jMainMenu, gridBagConstraints);

        jPromotorMenu.setAlignmentX(0.0F);
        jPromotorMenu.setAlignmentY(0.0F);
        jPromotorMenu.setMaximumSize(new java.awt.Dimension(600, 500));
        jPromotorMenu.setMinimumSize(new java.awt.Dimension(600, 500));
        jPromotorMenu.setPreferredSize(new java.awt.Dimension(620, 522));
        jPromotorMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddIngressos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddIngressos.setText("ADICIONAR EVENTO");
        btnAddIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIngressosActionPerformed(evt);
            }
        });
        jPromotorMenu.add(btnAddIngressos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 40));

        bntRemoverIngresso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bntRemoverIngresso.setText("REMOVER EVENTO");
        bntRemoverIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverIngressoActionPerformed(evt);
            }
        });
        jPromotorMenu.add(bntRemoverIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 150, 40));

        btnEditarIngresso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditarIngresso.setText("EDITAR EVENTO");
        btnEditarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIngressoActionPerformed(evt);
            }
        });
        jPromotorMenu.add(btnEditarIngresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 150, 40));

        btnVoltar5.setText("VOLTAR");
        btnVoltar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar5ActionPerformed(evt);
            }
        });
        jPromotorMenu.add(btnVoltar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 95, -1));

        ImgMenu1.setMaximumSize(new java.awt.Dimension(520, 460));
        ImgMenu1.setMinimumSize(new java.awt.Dimension(520, 460));
        ImgMenu1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPromotorMenu.add(ImgMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jPromotorMenu, gridBagConstraints);

        jRemoverEvento.setAlignmentX(0.0F);
        jRemoverEvento.setAlignmentY(0.0F);
        jRemoverEvento.setMaximumSize(new java.awt.Dimension(600, 500));
        jRemoverEvento.setMinimumSize(new java.awt.Dimension(600, 500));
        jRemoverEvento.setPreferredSize(new java.awt.Dimension(620, 522));

        btnDeletar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 0, 51));
        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnVoltar1.setText("VOLTAR");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        lstEventos1.setModel(lista);
        lstEventos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEventos1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lstEventos1);

        lblEventos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEventos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventos1.setText("EVENTOS");

        lblGuiche1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGuiche1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuiche1.setText("DELETE");

        txtInfoEvento1.setEditable(false);
        txtInfoEvento1.setColumns(20);
        txtInfoEvento1.setRows(5);
        jScrollPane5.setViewportView(txtInfoEvento1);

        lblInfoEvento1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfoEvento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoEvento1.setText("Informações do Evento");

        javax.swing.GroupLayout jRemoverEventoLayout = new javax.swing.GroupLayout(jRemoverEvento);
        jRemoverEvento.setLayout(jRemoverEventoLayout);
        jRemoverEventoLayout.setHorizontalGroup(
            jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRemoverEventoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblEventos1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(jRemoverEventoLayout.createSequentialGroup()
                .addGroup(jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRemoverEventoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jRemoverEventoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jRemoverEventoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInfoEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jRemoverEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar1)
                        .addGap(141, 141, 141)
                        .addComponent(lblGuiche1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jRemoverEventoLayout.setVerticalGroup(
            jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRemoverEventoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar1)
                    .addComponent(lblGuiche1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblEventos1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jRemoverEventoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblInfoEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jRemoverEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRemoverEventoLayout.createSequentialGroup()
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))))
                .addGap(96, 96, 96))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jRemoverEvento, gridBagConstraints);

        jGuicheAlterar.setAlignmentX(0.0F);
        jGuicheAlterar.setAlignmentY(0.0F);
        jGuicheAlterar.setMaximumSize(new java.awt.Dimension(600, 500));
        jGuicheAlterar.setMinimumSize(new java.awt.Dimension(600, 500));
        jGuicheAlterar.setPreferredSize(new java.awt.Dimension(620, 522));

        btnAlterar.setText("Alterar Evento");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnVoltar3.setText("VOLTAR");
        btnVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar3ActionPerformed(evt);
            }
        });

        lstAlterarEventos.setModel(lista);
        lstAlterarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAlterarEventosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(lstAlterarEventos);

        lblEventos2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEventos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventos2.setText("EVENTOS");

        lblGuiche2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGuiche2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuiche2.setText("GUICHE");

        lblAlterarArtista.setText("Artista");

        lblAlterarData.setText("Data (DD/MM/AAAA)");

        jLabel11.setText("/");
        jLabel11.setToolTipText("");

        jLabel12.setText(":");

        lblAlterarCapacidadeMaxima.setText("Capacidade Máxima");

        lblAlterarLocalEvento.setText("Local do Evento");

        lblAlterarValor.setText("Valor R$");

        lblAlterarHorario.setText("Horário");

        jLabel13.setText("/");

        lblAlterarNomeEvento.setText("Nome do Evento");

        javax.swing.GroupLayout jGuicheAlterarLayout = new javax.swing.GroupLayout(jGuicheAlterar);
        jGuicheAlterar.setLayout(jGuicheAlterarLayout);
        jGuicheAlterarLayout.setHorizontalGroup(
            jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEventos2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar3)
                        .addGap(141, 141, 141)
                        .addComponent(lblGuiche2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAlterarLocalEvento)
                                            .addComponent(lblAlterarArtista)
                                            .addComponent(lblAlterarNomeEvento))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAlterarNomeEvento)
                                            .addComponent(txtAlterarArtista)
                                            .addComponent(txtAlterarLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAlterarHorario)
                                            .addComponent(lblAlterarData)
                                            .addComponent(lblAlterarValor)
                                            .addComponent(lblAlterarCapacidadeMaxima))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                                                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtAlterarHora)
                                                    .addComponent(txtAlterarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtAlterarMes)
                                                    .addComponent(txtAlterarMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtAlterarValor)
                                            .addComponent(txtAlterarCapMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAlterarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jGuicheAlterarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jGuicheAlterarLayout.setVerticalGroup(
            jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar3)
                    .addComponent(lblGuiche2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblEventos2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(jGuicheAlterarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarNomeEvento)
                            .addComponent(txtAlterarNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarArtista)
                            .addComponent(txtAlterarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarLocalEvento)
                            .addComponent(txtAlterarLocalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarData)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(txtAlterarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlterarMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlterarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarHorario)
                            .addComponent(txtAlterarHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlterarMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarValor)
                            .addComponent(txtAlterarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jGuicheAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlterarCapacidadeMaxima)
                            .addComponent(txtAlterarCapMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        Camadas.add(jGuicheAlterar, gridBagConstraints);

        getContentPane().add(Camadas, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIngressosActionPerformed

        jMenu.setVisible(false);
        jAdicionar.setVisible(true);
        jPromotorMenu.setVisible(false);
    }//GEN-LAST:event_btnAddIngressosActionPerformed


    private void bntRemoverIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverIngressoActionPerformed
        // Botao para remover um Evento
        jPromotorMenu.setVisible(false);
        jRemoverEvento.setVisible(true);

    }//GEN-LAST:event_bntRemoverIngressoActionPerformed


    private void btnComprarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarIngressoActionPerformed
        // TODO add your handling code here:
        jMenu.setVisible(false);
        jGuiche.setVisible(true);
    }//GEN-LAST:event_btnComprarIngressoActionPerformed


    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // TODO add your handling code here:

        jCarrinhoDeCompras.setVisible(true);
        jMenu.setVisible(false);
        lblTotalConta.setText("R$ " + totalCompra);
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed


    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        txtInfoEvento.setText("");
        jMenu.setVisible(true);
        jGuiche.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed


    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:

        AddInfoCarrinho();

        if (listaEventos.get(selecionado).getIngresso().getContIngressos() > 0) {
            if (quantComprado <= listaEventos.get(selecionado).getIngresso().getContIngressos()) {
                Carrinho compras = new Carrinho(nome, artista, local, valor, quantComprado,
                        new Data(dia, mes, ano), new Hora(hora, minuto));

                listaCarrinho.add(compras);
            }
        }

        totalCompra += listaEventos.get(selecionado).ComprarIngresso(quantComprado);
        mostrarEvento();

        DefaultTableModel modelo = (DefaultTableModel) jTableList.getModel();
        modelo.setNumRows(0);

        for (Carrinho carrinho : listaCarrinho) {
            modelo.addRow(new Object[]{
                carrinho.getNomeEvento(),
                carrinho.getValor(),
                carrinho.getQuantidade()
            });
        }
        
        txtQuantidade.setText("");

    }//GEN-LAST:event_btnComprarActionPerformed


    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        pegarInformacoes();

        listaEventos.add(new Evento(nome,
                new Data(dia, mes, ano),
                new Hora(hora, minuto), artista,
                new Local(local, capacidadePessoas)));
        listaEventos.get(posicao).setIngresso(valor);

        mostrarEvento();
        posicao++;

        limparCampos();

        jAdicionar.setVisible(false);
        jPromotorMenu.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void lstEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEventosMouseClicked
        // TODO add your handling code here:
        selecionado = lstEventos.getSelectedIndex();
        txtInfoEvento.setText(listaEventos.get(selecionado).toString());

    }//GEN-LAST:event_lstEventosMouseClicked

    private void btnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar2ActionPerformed
        // TODO add your handling code here:
        jPromotorMenu.setVisible(true);
        jAdicionar.setVisible(false);
    }//GEN-LAST:event_btnVoltar2ActionPerformed

    private void btnVoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar4ActionPerformed
        // TODO add your handling code here:
        jMenu.setVisible(false);
        jMainMenu.setVisible(true);
    }//GEN-LAST:event_btnVoltar4ActionPerformed

    private void btnVoltar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar5ActionPerformed
        // TODO add your handling code here:
        jMainMenu.setVisible(true);
        jPromotorMenu.setVisible(false);
    }//GEN-LAST:event_btnVoltar5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jMainMenu.setVisible(false);
        jPromotorMenu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jMainMenu.setVisible(false);
        jMenu.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnVoltar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar6ActionPerformed
        // TODO add your handling code here:
        jCarrinhoDeCompras.setVisible(false);
        jMenu.setVisible(true);
    }//GEN-LAST:event_btnVoltar6ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        selecionado = lstEventos1.getSelectedIndex();
        listaEventos.remove(selecionado);
        mostrarEvento();


    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        jRemoverEvento.setVisible(false);
        jPromotorMenu.setVisible(true);

    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void lstEventos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEventos1MouseClicked
        // TODO add your handling code here:
        selecionado = lstEventos1.getSelectedIndex();
        txtInfoEvento1.setText(listaEventos.get(selecionado).toString());
    }//GEN-LAST:event_lstEventos1MouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // ACAO DO BOTAO PARA ALTERAR OS EVENTOS

        selecionado = lstAlterarEventos.getSelectedIndex();
        AlterarInformacoes(selecionado);
        mostrarEvento();


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar3ActionPerformed
        // TODO add your handling code here:
        jGuicheAlterar.setVisible(false);
        jPromotorMenu.setVisible(true);
    }//GEN-LAST:event_btnVoltar3ActionPerformed

    private void lstAlterarEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAlterarEventosMouseClicked
        // TODO add your handling code here:

        selecionado = lstAlterarEventos.getSelectedIndex();

        MostrarInformacoes(selecionado);


    }//GEN-LAST:event_lstAlterarEventosMouseClicked

    private void btnEditarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIngressoActionPerformed
        // TODO add your handling code here:
        jGuicheAlterar.setVisible(true);
        jPromotorMenu.setVisible(false);
    }//GEN-LAST:event_btnEditarIngressoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        if(ingresso == null){
            ingresso = new InterfaceIngresso();
            ingresso.setLocationRelativeTo(null);
            ingresso.setVisible(true);
            ingresso.setResizable(false);
        } else{
            ingresso.setLocationRelativeTo(null);
            ingresso.setVisible(true);
            ingresso.setResizable(false);
        }
        
        ingresso.imprimirIngresso(listaCarrinho.get(selecionadoCarrinho));
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jTableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListMouseClicked
        // TODO add your handling code here:
        selecionadoCarrinho = jTableList.getSelectedRow();
        
    }//GEN-LAST:event_jTableListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalcaoIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalcaoIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalcaoIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalcaoIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bi = new BalcaoIngresso();
                bi.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Camadas;
    private javax.swing.JLabel ImgMenu;
    private javax.swing.JLabel ImgMenu1;
    private javax.swing.JLabel ImgMenu2;
    private javax.swing.JButton bntRemoverIngresso;
    private javax.swing.JButton btnAddIngressos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnComprarIngresso;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditarIngresso;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JButton btnVoltar3;
    private javax.swing.JButton btnVoltar4;
    private javax.swing.JButton btnVoltar5;
    private javax.swing.JButton btnVoltar6;
    private javax.swing.JPanel jAdicionar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jCarrinhoDeCompras;
    private javax.swing.JPanel jGuiche;
    private javax.swing.JPanel jGuicheAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMainMenu;
    private javax.swing.JPanel jMenu;
    private javax.swing.JPanel jPromotorMenu;
    private javax.swing.JPanel jRemoverEvento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableList;
    private javax.swing.JLabel lblAlterarArtista;
    private javax.swing.JLabel lblAlterarCapacidadeMaxima;
    private javax.swing.JLabel lblAlterarData;
    private javax.swing.JLabel lblAlterarHorario;
    private javax.swing.JLabel lblAlterarLocalEvento;
    private javax.swing.JLabel lblAlterarNomeEvento;
    private javax.swing.JLabel lblAlterarValor;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCapacidadeMaxima;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEventos;
    private javax.swing.JLabel lblEventos1;
    private javax.swing.JLabel lblEventos2;
    private javax.swing.JLabel lblGuiche;
    private javax.swing.JLabel lblGuiche1;
    private javax.swing.JLabel lblGuiche2;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblInfoEvento;
    private javax.swing.JLabel lblInfoEvento1;
    private javax.swing.JLabel lblLocalEvento;
    private javax.swing.JLabel lblNomeEvento;
    private javax.swing.JLabel lblQuatidade;
    private javax.swing.JLabel lblTotalConta;
    private javax.swing.JLabel lblValor;
    private javax.swing.JList<String> lstAlterarEventos;
    private javax.swing.JList<String> lstEventos;
    private javax.swing.JList<String> lstEventos1;
    private javax.swing.JTextField txtAlterarAno;
    private javax.swing.JTextField txtAlterarArtista;
    private javax.swing.JTextField txtAlterarCapMaxima;
    private javax.swing.JTextField txtAlterarDia;
    private javax.swing.JTextField txtAlterarHora;
    private javax.swing.JTextField txtAlterarLocalEvento;
    private javax.swing.JTextField txtAlterarMes;
    private javax.swing.JTextField txtAlterarMinuto;
    private javax.swing.JTextField txtAlterarNomeEvento;
    private javax.swing.JTextField txtAlterarValor;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtCapMaxima;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextArea txtInfoEvento;
    private javax.swing.JTextArea txtInfoEvento1;
    private javax.swing.JTextField txtLocalEvento;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtMinuto;
    private javax.swing.JTextField txtNomeEvento;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void menu() {

        jGuiche.setVisible(false);
        jAdicionar.setVisible(false);
        jCarrinhoDeCompras.setVisible(false);
        jPromotorMenu.setVisible(false);
        jMainMenu.setVisible(true);
        jMenu.setVisible(false);
        jRemoverEvento.setVisible(false);
        jGuicheAlterar.setVisible(false);

    }

    private void perfumaria() {
        ImgMenu.setIcon(new ImageIcon("imagens/Balcao-de-Ingresso.png"));
        ImgMenu1.setIcon(new ImageIcon("imagens/Balcao-de-Ingresso.png"));
        ImgMenu2.setIcon(new ImageIcon("imagens/Balcao-de-Ingresso.png"));

    }

    private void pegarInformacoes() {
        this.nome = txtNomeEvento.getText();
        this.dia = Integer.parseInt(txtDia.getText());
        this.mes = Integer.parseInt(txtMes.getText());
        this.ano = Integer.parseInt(txtAno.getText());
        this.hora = Integer.parseInt(txtHora.getText());
        this.minuto = Integer.parseInt(txtMinuto.getText());
        this.artista = txtArtista.getText();
        this.local = txtLocalEvento.getText();
        this.capacidadePessoas = Integer.parseInt(txtCapMaxima.getText());
        this.valor = Double.parseDouble(txtValor.getText());
    }

    private void AddInfoCarrinho() {
        nome = listaEventos.get(selecionado).getNome();
        dia = listaEventos.get(selecionado).getData().getDia();
        mes = listaEventos.get(selecionado).getData().getMes();
        ano = listaEventos.get(selecionado).getData().getAno();
        hora = listaEventos.get(selecionado).getHora().getHora();
        minuto = listaEventos.get(selecionado).getHora().getMinuto();
        artista = listaEventos.get(selecionado).getArtista();
        local = listaEventos.get(selecionado).getLocal().getEndereco();
        valor = listaEventos.get(selecionado).getIngresso().getValor();
        quantComprado = Integer.parseInt(txtQuantidade.getText());
    }

    private void AlterarInformacoes(int selecionado) {

        listaEventos.get(selecionado).setNome(txtAlterarNomeEvento.getText());
        listaEventos.get(selecionado).getData().setDia(Integer.parseInt(txtAlterarDia.getText()));
        listaEventos.get(selecionado).getData().setMes(Integer.parseInt(txtAlterarMes.getText()));
        listaEventos.get(selecionado).getData().setAno(Integer.parseInt(txtAlterarAno.getText()));
        listaEventos.get(selecionado).getHora().setHora(Integer.parseInt(txtAlterarHora.getText()));
        listaEventos.get(selecionado).getHora().setHora(Integer.parseInt(txtAlterarMinuto.getText()));
        listaEventos.get(selecionado).setArtista(txtAlterarArtista.getText());
        listaEventos.get(selecionado).getLocal().setEndereco(txtAlterarLocalEvento.getText());
        listaEventos.get(selecionado).getLocal().setCapacidadePessoas(Integer.parseInt(txtAlterarCapMaxima.getText()));
        listaEventos.get(selecionado).getIngresso().setValor(Double.parseDouble(txtAlterarValor.getText()));
    }

    private void MostrarInformacoes(int selecionado) {
        txtAlterarAno.setText(Integer.toString(listaEventos.get(selecionado).getData().getAno()));
        txtAlterarArtista.setText((listaEventos.get(selecionado).getArtista()));
        txtAlterarCapMaxima.setText(Integer.toString(listaEventos.get(selecionado).getLocal().getCapacidadePessoas()));
        txtAlterarDia.setText(Integer.toString(listaEventos.get(selecionado).getData().getDia()));
        txtAlterarMes.setText(Integer.toString(listaEventos.get(selecionado).getData().getDia()));
        txtAlterarHora.setText(Integer.toString(listaEventos.get(selecionado).getHora().getHora()));
        txtAlterarLocalEvento.setText((listaEventos.get(selecionado).getLocal().getEndereco()));
        txtAlterarMinuto.setText(Integer.toString(listaEventos.get(selecionado).getHora().getMinuto()));
        txtAlterarNomeEvento.setText((listaEventos.get(selecionado).getNome()));
        txtAlterarValor.setText(Double.toString(listaEventos.get(selecionado).getIngresso().getValor()));
    }

    private void limparCampos() {
        txtNomeEvento.setText("");
        txtDia.setText("");
        txtMes.setText("");
        txtAno.setText("");
        txtArtista.setText("");
        txtCapMaxima.setText("");
        txtHora.setText("");
        txtLocalEvento.setText("");
        txtMinuto.setText("");
        txtQuantidade.setText("");
        txtValor.setText("");
        txtQuantidade.setText("");
    }

    private void mostrarEvento() {
        lista.removeAllElements();
        for (Evento evento : listaEventos) {
            if (evento.getIngresso().getContIngressos() == 0) {
                lista.addElement(evento.getNome() + "   ESGOTADO");
            } else {
                lista.addElement(evento.getNome());
            }
        }
    }

}
